### ISSUE TITLE
React.Router 3.1.0 no longer avaliable

### ISSUE THREAD

**Issue by GiraffeCoding** [gunnim/Umbraco-React-Router-SSR#1]
Hi,

Just tried to restore the nuget packages for this and the React.Router is no longer available which stops the solution from being rebuilt:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Umbraco.Site: Unable to find version '3.1.0' of package 'React.Router'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'React.Router.3.1.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'React.Router.3.1.0' is not found on source 'https://api.nuget.org/v3/index.json'.
.				
`
Can you upload the missing file/s, if not what else should be used in its place.

Thanks for your help.

**Comment by gunnim** [comment]
My pull request has been accepted but a new release has not yet been published.

You can either download the ReactJS.NET source and build or i could zip and send the nuget to you :)

**Comment by Ben-TangentDesign** [comment]
I've just cloned the ReactJS.NET from github but when i run (as admin) the dev-build.bat file i get the following error:

MSBUILD : error MSB1009: Project file does not exist.
Switch: build.proj
Press any key to continue . . .

build.proj is within the same folder.

**Comment by gunnim** [comment]
Not sure, seems like a local issue.

https://www.dropbox.com/s/9o73i998ed6sypy/output.zip?dl=0
This is a zip containg recent nugets built locally.
nugets themselves can be opened as zip archives if you want to get at the dlls

**Comment by GiraffeCoding** [comment]
Thanks for those files.
Managed to load the React.Router into the solution but now when running the solution getting the following error:

Method not found: 'React.IReactEnvironment React.ReactEnvironment.get_GetCurrentOrThrow()'.

Nothing changed and ran through the npm install and webpack cmd's 

error related to this code:

`@Html.ReactRouterWithContext("Routing", new { })`

Doesn't seem to be finding the global "Routing" 
`global['Routing'] = Routing;`

**Comment by gunnim** [comment]
I'll take a better look and try to update the demo this week or weekend.

**Comment by GiraffeCoding** [comment]
Thank you, that would be greatly appreciated

**Comment by gunnim** [comment]
Got it working with the latest build of reactjs.net, I'll clean it up once we get an official release!

Keep me posted if you have problems and if you find a use for the react router support maybe give daniel lo nigro a nudge on his project or twitter to release the damn thing :D

**Comment by gunnim** [comment]
Just updated with the official release of react router support and everything seems to be working :)
